[package]
name = "factor"
version = "0.1.1"
authors = ["Michael Lamparski <me@this.isnt.really.my.email.org>"]

[profile.release]
debug = true

[dependencies]
num = "0.1"
num-bigint = "0.1"
rand = "0.3"
bit-set = "0.2"
