[package]
name = "factor"
version = "0.1.1"
authors = ["Michael Lamparski <me@this.isnt.really.my.email.org>"]

[profile.release]
debug = true

[dependencies]
num = { version = "0.2", features = ["rand"] }
rand = "0.6.3"
bit-set = "0.2"

[dev-dependencies]
rand_xorshift = "0.1.1"
